const queries = {
	insertUser : 'INSERT INTO users (fullName,email,phoneNumber,national_id,passportUrl,password) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *',
	userExist: 'SELECT * FROM users WHERE national_id=$1',
	partyExist: 'SELECT * FROM parties WHERE name=$1 or logoUrl=$2',
	insertParty: 'INSERT INTO parties (logoUrl, name, hqAddress) VALUES ($1, $2, $3) RETURNING *',
	getParties: 'SELECT * FROM parties',
	getParty: 'SELECT * FROM parties where id=$1',
	deleteParty: 'DELETE FROM parties where id=$1',
	editParty: 'UPDATE parties SET logoUrl=$1, name=$2, hqAddress=$3 WHERE id=$4 RETURNING *',
	officeExist: 'SELECT * FROM offices where type=$1 AND name=$2',
	insertOffice: 'INSERT INTO offices (type, name) VALUES ($1, $2) returning *',
	getOffices: 'SELECT * FROM offices',
	getOffice: 'SELECT * FROM offices where id=$1',
	deleteOffice: 'DELETE FROM offices where id=$1',
	editOffice: 'UPDATE offices SET type=$1, name=$2 WHERE id=$3 RETURNING *',
	insertCandidate: 'INSERT INTO candidates (officeId, candidate_name) VALUES ($1, $2) RETURNING *',
	candidateExist: 'SELECT candidate_name, officeId FROM candidates WHERE candidate_name=$1 AND officeId=$2',
	candidateName: 'SELECT * FROM candidates WHERE candidate_name=$1 and officeId=$2',
	vote: 'INSERT INTO votes (office_name, candidate_name, voter_id) VALUES($1, $2, $3) RETURNING *',
	checkVotes: 'SELECT office_name, voter_id FROM votes WHERE office_name=$1 AND voter_id=$2',
	votedFor: 'SELECT * FROM votes WHERE voter_id=$1',
	insertPetition: 'INSERT INTO petitions (officeId, createdBy, text, evidence) VALUES($1, $2, $3, $4) RETURNING *',
	petitions: 'SELECT * FROM petitions WHERE createdBy=$1 AND officeId=$2',
	getEmail: 'SELECT email FROM users WHERE email=$1',
	numberOfVotes: 'SELECT count(voter_id) as total_votes FROM votes WHERE candidate_name=$1',
	candidates: 'SELECT * FROM candidates WHERE officeId=$1',
	office_name: 'SELECT * FROM votes WHERE office_name=$1'
}
export default queries;
